services:
  opengauss:
    image: opengauss/opengauss:5.0.0
    container_name: opengauss-db
    restart: always
    privileged: true
    environment:
      GS_PASSWORD: Gauss@123
      GS_NODENAME: opengauss
    ports:
      - "5432:5432"
    volumes:
      - opengauss-data:/var/lib/opengauss
    shm_size: "1gb"
    tmpfs:
      - /tmp:size=1G

volumes:
  opengauss-data:
    driver: local
